version: 2

defaults: &defaults
  docker:
    - image: cimg/clojure:1.10.3

jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - project-{{ checksum "deps.edn" }}
            - project

      - run:
          name: Run tests
          command: ./bin/kaocha.sh

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ./.cpcache
          key: project-{{ checksum "deps.edn" }}

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test
